### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by theSage21** [libhide/ml-spam-filter#1]
I think you were going for clarity this time around. In that case the code is awesome! In ML / DA however you've got to speed up the time it takes to test out a new solution. Suppose you changed the algo a little. How long would it take for you to test it out?

I've made some speed changes at https://github.com/theSage21/ml-spam-filter/tree/nsf. Take a look when you are free.

Also, when you've understood the concepts it would be much nicer to use something like [CountVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html). It's faster and a one liner.

So far pretty good though!

**Comment by libhide** [comment]
Thanks for this! Could you send across a pull request so I can merge the changes you made? Also, yup, will look into CountVectorizer next.
